Fix nonsensical CronetInterceptor.Builder#build method visibility
RequestResponseConverter is not a public class, so it doesn't make sense to have a public method that references it in its signature. In practice it looks like this method is an implementation detail that is only supposed to be called by the internal RequestResponseConverterBasedBuilder superclass. Users are supposed to call the public build() method that comes from the superclass.

This also makes CronetInterceptor.Builder consistent with CronetCallFactory.Builder in this regard.

This fixes the following error when attempting to run this codebase through Metalava:

  com/google/net/cronet/okhttptransport/CronetInterceptor.java:138: error: Class com.google.net.cronet.okhttptransport.RequestResponseConverter is not public but was referenced (in parameter type) from public parameter converter in com.google.net.cronet.okhttptransport.CronetInterceptor.Builder.build(com.google.net.cronet.okhttptransport.RequestResponseConverter converter) [ReferencesHidden]

PiperOrigin-RevId: 853739637